In [1]:
import sys
# sys.path.append('../code') # code
sys.path.append('../') #201910

from localconfig import BASE_PATH,EXPS
EXP=EXPS[0]
print(EXP)
print(BASE_PATH)


C9999_20191031
/Users/KozSakk/Documents/research/sakurayama/201910


In [2]:
import sys
from pprint import pprint
pprint(sys.path)

import pathlib
from maxone_code.data import RawFile

import numpy as np
np.set_printoptions(threshold=1050)

from maxone_code.spikedetect import BandPassFilter
from maxone_code.util import SAMPLING_FREQ
from maxone_code.data import CfgFile

['/Users/KozSakk/Documents/research/sakurayama/201910/ipynb',
 '/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python37.zip',
 '/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7',
 '/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload',
 '',
 '/Users/KozSakk/venv/lib/python3.7/site-packages',
 '/Users/KozSakk/venv/lib/python3.7/site-packages/IPython/extensions',
 '/Users/KozSakk/.ipython',
 '../']


In [3]:
path= pathlib.Path(BASE_PATH).joinpath('data',EXP,'selectelectrode','raw','test1.raw.h5')

In [4]:
raw_data=RawFile(str(path))
print(raw_data.sig.shape)
print(raw_data.sig.shape[1] //SAMPLING_FREQ)
print(raw_data.channelmap[-1]+1)

(1028, 6000000)
300
962


In [8]:
pwd

'/Users/KozSakk/Documents/research/sakurayama/201910/ipynb'

In [14]:
path="/Users/KozSakk/Downloads/190826.cfg"
cfg = CfgFile(path)

In [26]:
import parse
file = open(path, "r")
source = file.readline()

all_electrodes = []
for i,j in parse.findall("{:d}({:d})", source):
    all_electrodes.append((i,j))
    
    
chan_elec_table = np.full(1024,-1)
for i,j in parse.findall("{:d}({:d})", source):
    chan_elec_table[i] = j

In [32]:
np.where(chan_elec_table>10)[0]

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
         44,   45,   46,   47,   48,   49,   50,   51,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  109,  110,  111,
        112,  113,  114,  115,  116,  117,  118,  119,  120,  121,  122,
        123,  124,  126,  127,  130,  131,  134,  135,  137,  138,  139,
        142,  143,  146,  147,  150,  151,  154,  155,  158,  159,  161,
        162,  163,  164,  166,  167,  169,  170,  1

In [29]:
chan_elec_table[chan_elec_table>=0]

array([17915, 13194, 13200, 18158, 22325, 20581, 18349, 16233, 12347,
       11380, 18134, 24295, 17468, 14008, 18576, 17717, 12328, 18382,
       18568, 17721, 17469, 16408, 21666, 20118, 16945, 18608, 19014,
       16411, 11472,  9871, 24288, 18159, 25176, 17940, 20330, 16257,
       24734, 17474, 22546, 14955, 24742, 18825, 11710, 20577, 16593,
        8792, 10376, 18601, 24296, 17944, 24304, 17947, 13141, 20113,
       19891, 16280, 11434, 20117, 18569, 13674, 10773, 25598, 20337,
       18584, 12732, 18708, 18366, 20768, 18606, 21875, 20131, 18127,
       12286, 17254, 18593, 18146, 18143, 17176, 18167, 18142, 11206,
       20993, 18808, 12994,  7442, 21435, 21011, 17927,  7032, 17696,
       21217, 17695, 16014, 17700, 21007, 22532, 12289, 21873, 25186,
       18126, 18168, 23834, 21436, 20997,  9451, 21013, 19465, 17722,
       18580, 21887, 16551, 12955, 21178, 21891, 17465,  9013, 22301,
       20157, 13648, 17726, 21884, 22544, 18558, 22534, 22548, 17026,
       22335, 19678,

828

In [16]:
all_electrodes

[]

In [10]:
cfg.record_electrode

array([17915, 13194, 13200, 18158, 22325, 20581, 18349, 16233, 12347,
       11380, 18134, 24295, 17468, 14008, 18576, 17717, 12328, 18382,
       18568, 17721, 17469, 16408, 21666, 20118, 16945, 18608, 19014,
       16411, 11472,  9871, 24288, 18159, 25176, 17940, 20330, 16257,
       24734, 17474, 22546, 14955, 24742, 18825, 11710, 20577, 16593,
        8792, 10376, 18601, 24296, 17944, 24304, 17947, 13141, 20113,
       19891, 16280, 11434, 20117, 18569, 13674, 10773, 25598, 20337,
       18584, 12732, 18708, 18366, 20768, 18606, 21875, 20131, 18127,
       12286, 17254, 18593, 18146, 18143, 17176, 18167, 18142, 11206,
       20993, 18808, 12994,  7442, 21435, 21011, 17927,  7032, 17696,
       21217, 17695, 16014, 17700, 21007, 22532, 12289, 21873, 25186,
       18126, 18168, 23834, 21436, 20997,  9451, 21013, 19465, 17722,
       18580, 21887, 16551, 12955, 21178, 21891, 17465,  9013, 22301,
       20157, 13648, 17726, 21884, 22544, 18558, 22534, 22548, 17026,
       22335, 19678,

In [6]:
sig = raw_data.sig
start = 20
sec = 250

size_of_recored_eles=raw_data.channelmap[-1]+1
startframe=20000*start
length=20000*sec
# length=1000

i = 200
lfp = np.zeros((length),dtype=sig.dtype)
sig.read_direct(lfp,source_sel=np.s_[raw_data.channelmap[i],startframe:startframe+length],dest_sel=np.s_[0:length])


In [7]:
fil=BandPassFilter(lowcut=30,highcut=3000,fs=20000)
bpf = raw_data.lsb_uV*fil.filter(lfp)

In [35]:
y = np.random.random((5,9))

In [36]:
ids = bpf > 0.0
# ids

In [37]:
np.median(bpf)

0.011938174346304923

In [22]:
help(np.median)

Help on function median in module numpy:

median(a, axis=None, out=None, overwrite_input=False, keepdims=False)
    Compute the median along the specified axis.
    
    Returns the median of the array elements.
    
    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    axis : {int, sequence of int, None}, optional
        Axis or axes along which the medians are computed. The default
        is to compute the median along a flattened version of the array.
        A sequence of axes is supported since version 1.9.0.
    out : ndarray, optional
        Alternative output array in which to place the result. It must
        have the same shape and buffer length as the expected output,
        but the type (of the output) will be cast if necessary.
    overwrite_input : bool, optional
       If True, then allow use of memory of input array `a` for
       calculations. The input array will be modified by the call to
       `med